name: Build and push Docker image to ECR (private)

on:
  push:
    branches:
      - release/v*
      - feature/*

permissions:
  contents: read

env:
  AWS_REGION: eu-north-1
  ECR_REPOSITORY: 288509344804.dkr.ecr.eu-north-1.amazonaws.com
  IMAGE_NAME: core.postgres-operator

jobs:
  ci:
    name: Build and push Docker image to ECR
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout main repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "^1.25.3"
          cache-dependency-path: go.sum

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.CORE_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.CORE_AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Parse release version from Git commit message
        run: |
          readonly VERSION_REGEX="v[0-9]+\.[0-9]+\.[0-9]+"

          VERSION_PREV="$(git for-each-ref --sort=creatordate --format "%(refname:lstrip=2)" refs/tags | grep -E "^${VERSION_REGEX}$" | tail -1)"

          if [[ -z "${VERSION_PREV}" ]]; then
            >&2 echo "At least one version tag is required in the repository."
            >&2 echo "Tag a Git commit on the main branch manually before running the workflow."
            exit 1
          fi

          readonly GIT_BRANCH="${GITHUB_REF#refs/heads/}"

          GIT_BRANCH_SANITIZED="${GIT_BRANCH}"
          GIT_BRANCH_SANITIZED="${GIT_BRANCH_SANITIZED//\//-}"
          GIT_BRANCH_SANITIZED="${GIT_BRANCH_SANITIZED//_/-}"
          VERSION="${VERSION_PREV}-${GITHUB_SHA:0:7}-${GIT_BRANCH_SANITIZED}"
          VERSION="${VERSION:0:128}"
          VERSION="${VERSION%-}"

          echo "VERSION=${VERSION}" >> "${GITHUB_ENV}"

      - name: Login to ECR
        uses: aws-actions/amazon-ecr-login@v2
        with:
          registry-type: private

      - name: Run unit tests
        run: make deps mocks test

      - name: Build and push Docker image
        run: |
          export IMAGE="${ECR_REPOSITORY}/${IMAGE_NAME}"
          export TAG="${VERSION}"
          export VERSION="${VERSION}"

          make docker
          docker push "${IMAGE}:${TAG}"
