name: Build and push Docker image to ECR (public)

on:
  push:
    branches:
      - master

permissions:
  contents: write

env:
  AWS_REGION: us-east-1
  ECR_REPOSITORY: public.ecr.aws/edenlabllc
  GIT_USERNAME: github-actions
  GIT_EMAIL: github-actions@github.com
  IMAGE_NAME: core.postgres-operator

jobs:
  ci:
    name: Build and push Docker image to ECR
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout main repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "^1.25.3"
          cache-dependency-path: go.sum

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.CORE_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.CORE_AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Parse release version from Git commit history
        run: |
          echo "Git commit message:"
          GIT_COMMIT_MSG="$(git log -1 --pretty=format:"%s")"
          echo "${GIT_COMMIT_MSG}"

          VERSION_REGEX="^Merge pull request #[0-9]+ from ${GITHUB_REPOSITORY_OWNER}/release/(v[0-9]+\.[0-9]+\.[0-9]+)$"
          if [[ ! "${GIT_COMMIT_MSG}" =~ ${VERSION_REGEX} ]]; then
            >&2 echo "Pushes to master should be done via merges of PR requests from release branches only."
            >&2 echo "  release branch - release/vN.N.N"
            >&2 echo "The expected message format (will be used for parsing a release tag):"
            >&2 echo "Merge pull request #N from ${GITHUB_REPOSITORY_OWNER}/release/vN.N.N"
            exit 1
          fi

          VERSION="${BASH_REMATCH[1]}"
          echo "VERSION=${VERSION}" >> "${GITHUB_ENV}"

      - name: Login to ECR
        uses: aws-actions/amazon-ecr-login@v2
        with:
          registry-type: public

      - name: Run unit tests
        run: make deps mocks test

      - name: Build and push Docker image
        run: |
          export IMAGE="${ECR_REPOSITORY}/${IMAGE_NAME}"
          export TAG="${VERSION}"
          export VERSION="${VERSION}"

          make docker
          docker push "${IMAGE}:${TAG}"

      - name: Create Git tag and GitHub release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "${GIT_USERNAME}"
          git config user.email "${GIT_EMAIL}"

          if git rev-parse "${VERSION}" >/dev/null 2>&1; then
            echo "Git tag ${VERSION} already exists"
          else
            git tag -m "${VERSION}" "${VERSION}"
            git push origin "${VERSION}"
          fi

          gh release view "${VERSION}" >/dev/null 2>&1 \
            || gh release create "${VERSION}" --title "${VERSION}" --generate-notes
